
keyBindings = { }

from keyids import KEYIDS
from Components.config import config
from Components.RcModel import rc_model

keyDescriptions = [{
		KEYIDS["BTN_0"]: ("UP", "fp"),
		KEYIDS["BTN_1"]: ("DOWN", "fp"),
		KEYIDS["KEY_OK"]: ("OK", ""),
		KEYIDS["KEY_UP"]: ("UP",),
		KEYIDS["KEY_DOWN"]: ("DOWN",),
		KEYIDS["KEY_POWER"]: ("POWER",),
		KEYIDS["KEY_RED"]: ("RED",),
		KEYIDS["KEY_BLUE"]: ("BLUE",),
		KEYIDS["KEY_GREEN"]: ("GREEN",),
		KEYIDS["KEY_YELLOW"]: ("YELLOW",),
		KEYIDS["KEY_MENU"]: ("MENU",),
		KEYIDS["KEY_LEFT"]: ("LEFT",),
		KEYIDS["KEY_RIGHT"]: ("RIGHT",),
		KEYIDS["KEY_VIDEO"]: ("PVR",),
		KEYIDS["KEY_INFO"]: ("INFO",),
		KEYIDS["KEY_AUDIO"]: ("YELLOW",),
		KEYIDS["KEY_TV"]: ("TV",),
		KEYIDS["KEY_RADIO"]: ("RADIO",),
		KEYIDS["KEY_TEXT"]: ("TEXT",),
		KEYIDS["KEY_NEXT"]: ("ARROWRIGHT",),
		KEYIDS["KEY_PREVIOUS"]: ("ARROWLEFT",),
		KEYIDS["KEY_PREVIOUSSONG"]: ("REWIND",),
		KEYIDS["KEY_PLAYPAUSE"]: ("PLAYPAUSE",),
		KEYIDS["KEY_PLAY"]: ("PLAYPAUSE",),
		KEYIDS["KEY_NEXTSONG"]: ("FASTFORWARD",),
		KEYIDS["KEY_CHANNELUP"]: ("BOUQUET+",),
		KEYIDS["KEY_CHANNELDOWN"]: ("BOUQUET-",),
		KEYIDS["KEY_0"]: ("0",),
		KEYIDS["KEY_1"]: ("1",),
		KEYIDS["KEY_2"]: ("2",),
		KEYIDS["KEY_3"]: ("3",),
		KEYIDS["KEY_4"]: ("4",),
		KEYIDS["KEY_5"]: ("5",),
		KEYIDS["KEY_6"]: ("6",),
		KEYIDS["KEY_7"]: ("7",),
		KEYIDS["KEY_8"]: ("8",),
		KEYIDS["KEY_9"]: ("9",),
		KEYIDS["KEY_EXIT"]: ("EXIT",),
		KEYIDS["KEY_STOP"]: ("STOP",),
		KEYIDS["KEY_RECORD"]: ("RECORD",)
	},
	{
		KEYIDS["BTN_0"]: ("UP", "fp"),
		KEYIDS["BTN_1"]: ("DOWN", "fp"),
		KEYIDS["KEY_OK"]: ("OK", ""),
		KEYIDS["KEY_UP"]: ("UP",),
		KEYIDS["KEY_DOWN"]: ("DOWN",),
		KEYIDS["KEY_POWER"]: ("POWER",),
		KEYIDS["KEY_RED"]: ("RED",),
		KEYIDS["KEY_BLUE"]: ("BLUE",),
		KEYIDS["KEY_GREEN"]: ("GREEN",),
		KEYIDS["KEY_YELLOW"]: ("YELLOW",),
		KEYIDS["KEY_MENU"]: ("MENU",),
		KEYIDS["KEY_LEFT"]: ("LEFT",),
		KEYIDS["KEY_RIGHT"]: ("RIGHT",),
		KEYIDS["KEY_VIDEO"]: ("VIDEO",),
		KEYIDS["KEY_INFO"]: ("INFO",),
		KEYIDS["KEY_AUDIO"]: ("AUDIO",),
		KEYIDS["KEY_TV"]: ("TV",),
		KEYIDS["KEY_RADIO"]: ("RADIO",),
		KEYIDS["KEY_TEXT"]: ("TEXT",),
		KEYIDS["KEY_NEXT"]: ("ARROWRIGHT",),
		KEYIDS["KEY_PREVIOUS"]: ("ARROWLEFT",),
		KEYIDS["KEY_PREVIOUSSONG"]: ("RED", "SHIFT"),
		KEYIDS["KEY_PLAYPAUSE"]: ("YELLOW", "SHIFT"),
		KEYIDS["KEY_PLAY"]: ("GREEN", "SHIFT"),
		KEYIDS["KEY_NEXTSONG"]: ("BLUE", "SHIFT"),
		KEYIDS["KEY_CHANNELUP"]: ("BOUQUET+",),
		KEYIDS["KEY_CHANNELDOWN"]: ("BOUQUET-",),
		KEYIDS["KEY_0"]: ("0",),
		KEYIDS["KEY_1"]: ("1",),
		KEYIDS["KEY_2"]: ("2",),
		KEYIDS["KEY_3"]: ("3",),
		KEYIDS["KEY_4"]: ("4",),
		KEYIDS["KEY_5"]: ("5",),
		KEYIDS["KEY_6"]: ("6",),
		KEYIDS["KEY_7"]: ("7",),
		KEYIDS["KEY_8"]: ("8",),
		KEYIDS["KEY_9"]: ("9",),
		KEYIDS["KEY_EXIT"]: ("EXIT",),
		KEYIDS["KEY_STOP"]: ("TV", "SHIFT"),
		KEYIDS["KEY_RECORD"]: ("RADIO", "SHIFT"),
		KEYIDS["KEY_EPG"]: ("EPG",),
		KEYIDS["KEY_REWIND"]: ("REWIND",),
		KEYIDS["KEY_FASTFORWARD"]: ("FASTFORWARD",)
	},
	{
		KEYIDS["BTN_0"]: ("UP", "fp"),
		KEYIDS["BTN_1"]: ("DOWN", "fp"),
		KEYIDS["KEY_OK"]: ("OK", ""),
		KEYIDS["KEY_UP"]: ("UP",),
		KEYIDS["KEY_DOWN"]: ("DOWN",),
		KEYIDS["KEY_POWER"]: ("POWER",),
		KEYIDS["KEY_RED"]: ("RED",),
		KEYIDS["KEY_BLUE"]: ("BLUE",),
		KEYIDS["KEY_GREEN"]: ("GREEN",),
		KEYIDS["KEY_YELLOW"]: ("YELLOW",),
		KEYIDS["KEY_MENU"]: ("MENU",),
		KEYIDS["KEY_LEFT"]: ("LEFT",),
		KEYIDS["KEY_RIGHT"]: ("RIGHT",),
		KEYIDS["KEY_VIDEO"]: ("PVR",),
		KEYIDS["KEY_INFO"]: ("INFO",),
		KEYIDS["KEY_AUDIO"]: ("AUDIO",),
		KEYIDS["KEY_TV"]: ("TV",),
		KEYIDS["KEY_RADIO"]: ("RADIO",),
		KEYIDS["KEY_TEXT"]: ("TEXT",),
		KEYIDS["KEY_NEXT"]: ("ARROWRIGHT",),
		KEYIDS["KEY_PREVIOUS"]: ("ARROWLEFT",),
		KEYIDS["KEY_PREVIOUSSONG"]: ("REWIND",),
		KEYIDS["KEY_PLAYPAUSE"]: ("PAUSE",),
		KEYIDS["KEY_PLAY"]: ("PLAY",),
		KEYIDS["KEY_NEXTSONG"]: ("FASTFORWARD",),
		KEYIDS["KEY_CHANNELUP"]: ("BOUQUET+",),
		KEYIDS["KEY_CHANNELDOWN"]: ("BOUQUET-",),
		KEYIDS["KEY_0"]: ("0",),
		KEYIDS["KEY_1"]: ("1",),
		KEYIDS["KEY_2"]: ("2",),
		KEYIDS["KEY_3"]: ("3",),
		KEYIDS["KEY_4"]: ("4",),
		KEYIDS["KEY_5"]: ("5",),
		KEYIDS["KEY_6"]: ("6",),
		KEYIDS["KEY_7"]: ("7",),
		KEYIDS["KEY_8"]: ("8",),
		KEYIDS["KEY_9"]: ("9",),
		KEYIDS["KEY_EXIT"]: ("EXIT",),
		KEYIDS["KEY_STOP"]: ("STOP",),
		KEYIDS["KEY_RECORD"]: ("RECORD",),
		KEYIDS["KEY_PAGEUP"]: ("PAGEUP",),
		KEYIDS["KEY_PAGEDOWN"]: ("PAGEDOWN",)
	},
	{  # for remotes with ID 3 (Spark RC12)
		KEYIDS["KEY_POWER"]: ("POWER",),
		KEYIDS["KEY_V"]: ("V.FORMAT",),
		KEYIDS["KEY_AUX"]: ("TV/SAT",),
		KEYIDS["KEY_TIME"]: ("TIME",),
		KEYIDS["KEY_MUTE"]: ("MUTE",),
		KEYIDS["KEY_0"]: ("0",),
		KEYIDS["KEY_1"]: ("1",),
		KEYIDS["KEY_2"]: ("2",),
		KEYIDS["KEY_3"]: ("3",),
		KEYIDS["KEY_4"]: ("4",),
		KEYIDS["KEY_5"]: ("5",),
		KEYIDS["KEY_6"]: ("6",),
		KEYIDS["KEY_7"]: ("7",),
		KEYIDS["KEY_8"]: ("8",),
		KEYIDS["KEY_9"]: ("9",),
		KEYIDS["KEY_TV2"]: ("TV/RADIO",),
		KEYIDS["KEY_BACK"]: ("RECALL",),
		KEYIDS["KEY_PAGEUP"]: ("PAGE+",),
		KEYIDS["KEY_PAGEDOWN"]: ("PAGE-",),
		KEYIDS["KEY_FIND"]: ("FIND",),
		KEYIDS["KEY_ARCHIVE"]: ("FOLDER",),
		KEYIDS["KEY_VOLUMEUP"]: ("VOL+",),
		KEYIDS["KEY_VOLUMEDOWN"]: ("VOL-",),
		KEYIDS["KEY_MENU"]: ("MENU",),
		KEYIDS["KEY_INFO"]: ("INFO",),
		KEYIDS["KEY_UP"]: ("UP",),
		KEYIDS["KEY_DOWN"]: ("DOWN",),
		KEYIDS["KEY_LEFT"]: ("LEFT",),
		KEYIDS["KEY_RIGHT"]: ("RIGHT",),
		KEYIDS["KEY_OK"]: ("OK", ""),
		KEYIDS["KEY_HOME"]: ("EXIT",),
		KEYIDS["KEY_EPG"]: ("EPG",),
		KEYIDS["KEY_FAVORITES"]: ("FAV",),
		KEYIDS["KEY_SAT"]: ("SAT",),
		KEYIDS["KEY_RED"]: ("RED",),
		KEYIDS["KEY_GREEN"]: ("GREEN",),
		KEYIDS["KEY_YELLOW"]: ("YELLOW",),
		KEYIDS["KEY_BLUE"]: ("BLUE",),
		KEYIDS["KEY_RECORD"]: ("RECORD",),
		KEYIDS["KEY_STOP"]: ("STOP",),
		KEYIDS["KEY_PLAY"]: ("PLAY",),
		KEYIDS["KEY_PAUSE"]: ("PAUSE",),
		KEYIDS["KEY_FASTFORWARD"]: ("FASTFORWARD",),
		KEYIDS["KEY_REWIND"]: ("REWIND",),
		KEYIDS["KEY_PREVIOUS"]: ("ARROWLEFT",),
		KEYIDS["KEY_NEXT"]: ("ARROWRIGHT",),
		KEYIDS["KEY_F"]: ("FAST",),
		KEYIDS["KEY_SLOW"]: ("SLOW",),
		KEYIDS["KEY_P"]: ("PLAY_MODE",),
		KEYIDS["KEY_CLOSE"]: ("USB",),
		KEYIDS["KEY_T"]: ("Tms",),
		KEYIDS["KEY_F1"]: ("F1",),
		KEYIDS["KEY_F2"]: ("F2",),
		KEYIDS["KEY_F3"]: ("F3",),
		KEYIDS["KEY_OPEN"]: ("PORTAL",),
	},
	{  # for remotes with ID 4 (All Fortis)
		KEYIDS["KEY_MUTE"]: ("MUTE",),
		KEYIDS["KEY_POWER"]: ("STANDBY",),
		KEYIDS["KEY_ANGLE"]: ("VFORMAT",),
		KEYIDS["KEY_SCREEN"]: ("RESOLUTION",),
		KEYIDS["KEY_1"]: ("1BUTTON",),
		KEYIDS["KEY_2"]: ("2BUTTON",),
		KEYIDS["KEY_3"]: ("3BUTTON",),
		KEYIDS["KEY_4"]: ("4BUTTON",),
		KEYIDS["KEY_5"]: ("5BUTTON",),
		KEYIDS["KEY_6"]: ("6BUTTON",),
		KEYIDS["KEY_7"]: ("7BUTTON",),
		KEYIDS["KEY_8"]: ("8BUTTON",),
		KEYIDS["KEY_9"]: ("9BUTTON",),
		KEYIDS["KEY_HELP"]: ("INFO",),
		KEYIDS["KEY_0"]: ("0BUTTON",),
		KEYIDS["KEY_MEMO"]: ("RECALL",),
		KEYIDS["KEY_VOLUMEUP"]: ("VOLUMEUP",),
		KEYIDS["KEY_MENU"]: ("MENU",),
		KEYIDS["KEY_PAGEUP"]: ("CHANNELUP",),
		KEYIDS["KEY_VOLUMEDOWN"]: ("VOLUMEDOWN",),
		KEYIDS["KEY_HOME"]: ("EXIT",),
		KEYIDS["KEY_PAGEDOWN"]: ("CHANNELDOWN",),
		KEYIDS["KEY_UP"]: ("UP",),
		KEYIDS["KEY_LEFT"]: ("LEFT",),
		KEYIDS["KEY_OK"]: ("OK",),
		KEYIDS["KEY_RIGHT"]: ("RIGHT",),
		KEYIDS["KEY_DOWN"]: ("DOWN",),
		KEYIDS["KEY_TEEN"]: ("UPUP",),
		KEYIDS["KEY_EPG"]: ("EPG",),
		KEYIDS["KEY_TWEN"]: ("DOWNDOWN",),
		KEYIDS["KEY_REWIND"]: ("REWIND",),
		KEYIDS["KEY_PLAY"]: ("PLAY",),
		KEYIDS["KEY_FASTFORWARD"]: ("FASTFORWARD",),
		KEYIDS["KEY_PREVIOUS"]: ("LAST",),
		KEYIDS["KEY_RECORD"]: ("RECORD",),
		KEYIDS["KEY_NEXT"]: ("NEXT",),
		KEYIDS["KEY_DIRECTORY"]: ("OPEN",),
		KEYIDS["KEY_PAUSE"]: ("PAUSE",),
		KEYIDS["KEY_STOP"]: ("STOP",),
		KEYIDS["KEY_SELECT"]: ("CHECK",),
		KEYIDS["KEY_RED"]: ("RED",),
		KEYIDS["KEY_GREEN"]: ("GREEN",),
		KEYIDS["KEY_YELLOW"]: ("YELLOW",),
		KEYIDS["KEY_BLUE"]: ("BLUE",),
		KEYIDS["KEY_OPTION"]: ("PIP",),
		KEYIDS["KEY_GOTO"]: ("SWAP",),
#		KEYIDS["KEY_PIPSEL"]: ("PIP_SEL",), # PIP list
		KEYIDS["KEY_SLOW"]: ("SLEEP",),
		KEYIDS["KEY_FAVORITES"]: ("FAV",),
		KEYIDS["KEY_MODE"]: ("TVRADIO",),
		KEYIDS["KEY_SUBTITLE"]: ("LIST",),
		KEYIDS["KEY_TEXT"]: ("TEXT",),
		KEYIDS["KEY_ZOOM"]: ("ZOOM",),
	},
	{  # for remotes with ID 5 (Topfield TF77X0HDPVR)
		KEYIDS["KEY_POWER"]: ("STANDBY",),
		KEYIDS["KEY_MUTE"]: ("MUTE",),
		KEYIDS["KEY_ZOOM"]: ("V.FORMAT",),
		KEYIDS["KEY_SCREEN"]: ("A/R",),
		KEYIDS["KEY_AUX"]: ("AUX",),
		KEYIDS["KEY_1"]: ("1BUTTON",),
		KEYIDS["KEY_2"]: ("2BUTTON",),
		KEYIDS["KEY_3"]: ("3BUTTON",),
		KEYIDS["KEY_4"]: ("4BUTTON",),
		KEYIDS["KEY_5"]: ("5BUTTON",),
		KEYIDS["KEY_6"]: ("6BUTTON",),
		KEYIDS["KEY_7"]: ("7BUTTON",),
		KEYIDS["KEY_8"]: ("8BUTTON",),
		KEYIDS["KEY_9"]: ("9BUTTON",),
		KEYIDS["KEY_BACK"]: ("BACK",),
		KEYIDS["KEY_0"]: ("0BUTTON",),
		KEYIDS["KEY_HELP"]: ("INFO",),
		KEYIDS["KEY_LANGUAGE"]: ("AUDIO",),
		KEYIDS["KEY_SUBTITLE"]: ("SUBTITLE",),
		KEYIDS["KEY_TEXT"]: ("TEXT",),
		KEYIDS["KEY_MENU"]: ("MENU",),
		KEYIDS["KEY_EPG"]: ("GUIDE",),
		KEYIDS["KEY_UP"]: ("UP/P+",),
		KEYIDS["KEY_LEFT"]: ("LEFT/V-",),
		KEYIDS["KEY_OK"]: ("OK/LIST",),
		KEYIDS["KEY_RIGHT"]: ("RIGHT/V+",),
		KEYIDS["KEY_DOWN"]: ("DOWN/P-",),
		KEYIDS["KEY_HOME"]: ("EXIT",),
		KEYIDS["KEY_FAVORITES"]: ("FAV",),
		KEYIDS["KEY_RED"]: ("RED",),
		KEYIDS["KEY_GREEN"]: ("GREEN",),
		KEYIDS["KEY_YELLOW"]: ("YELLOW",),
		KEYIDS["KEY_BLUE"]: ("BLUE",),
		KEYIDS["KEY_REWIND"]: ("REWIND",),
		KEYIDS["KEY_PAUSE"]: ("PAUSE",),
		KEYIDS["KEY_PLAY"]: ("PLAY",),
		KEYIDS["KEY_FASTFORWARD"]: ("FASTFORWARD",),
		KEYIDS["KEY_RECORD"]: ("RECORD",),
		KEYIDS["KEY_STOP"]: ("STOP",),
		KEYIDS["KEY_SLOW"]: ("SLOWMOTION",),
		KEYIDS["KEY_LIST"]: ("RECORDLIST" ,),
		KEYIDS["KEY_SAT"]: ("SAT",),
		KEYIDS["KEY_PREVIOUS"]: ("STEPBACK",),
		KEYIDS["KEY_NEXT"]: ("STEPFORWARD",),
		KEYIDS["KEY_OPTION"]: ("MARK",),
		KEYIDS["KEY_TV2"]: ("TV/RADIO",),
		KEYIDS["KEY_ARCHIVE"]: ("USB",),
		KEYIDS["KEY_TIME"]: ("TIMER",),
		# Frontpanel keys
		KEYIDS["KEY_PAGEDOWN"]: ("CHANNELDOWN",),
		KEYIDS["KEY_PAGEUP"]: ("CHANNELUP",),
		KEYIDS["KEY_VOLUMEDOWN"]: ("VOLUMEDOWN",),
		KEYIDS["KEY_VOLUMEUP"]: ("VOLUMEUP",),
		KEYIDS["KEY_POWER"]: ("STANDBY",),
	},
	{  # for remotes with ID 6 (Kathrein UFS912)
		KEYIDS["KEY_MEDIA"]: ("MEDIA",),
		KEYIDS["KEY_ARCHIVE"]: ("ARCHIVE",),
		KEYIDS["KEY_MENU"]: ("MENU",),
		KEYIDS["KEY_RED"]: ("RED",),
		KEYIDS["KEY_GREEN"]: ("GREEN",),
		KEYIDS["KEY_YELLOW"]: ("YELLOW",),
		KEYIDS["KEY_BLUE"]: ("BLUE",),
		KEYIDS["KEY_HOME"]: ("EXIT",),
		KEYIDS["KEY_TEXT"]: ("TEXT",),
		KEYIDS["KEY_EPG"]: ("EPG",),
		KEYIDS["KEY_REWIND"]: ("REWIND",),
		KEYIDS["KEY_FASTFORWARD"]: ("FASTFORWARD",),
		KEYIDS["KEY_PLAY"]: ("PLAY",),
		KEYIDS["KEY_PAUSE"]: ("PAUSE",),
		KEYIDS["KEY_RECORD"]: ("RECORD",),
		KEYIDS["KEY_STOP"]: ("STOP",),
		KEYIDS["KEY_POWER"]: ("STANDBY",),
		KEYIDS["KEY_MUTE"]: ("MUTE",),
		KEYIDS["KEY_PAGEUP"]: ("CHANNELUP",),
		KEYIDS["KEY_PAGEDOWN"]: ("CHANNELDOWN",),
		KEYIDS["KEY_VOLUMEUP"]: ("VOLUMEUP",),
		KEYIDS["KEY_VOLUMEDOWN"]: ("VOLUMEDOWN",),
		KEYIDS["KEY_HELP"]: ("HELP",),
		KEYIDS["KEY_INFO"]: ("INFO",),
		KEYIDS["KEY_OK"]: ("OK",),
		KEYIDS["KEY_UP"]: ("UP",),
		KEYIDS["KEY_RIGHT"]: ("RIGHT",),
		KEYIDS["KEY_DOWN"]: ("DOWN",),
		KEYIDS["KEY_LEFT"]: ("LEFT",),
		KEYIDS["KEY_0"]: ("0BUTTON",),
		KEYIDS["KEY_1"]: ("1BUTTON",),
		KEYIDS["KEY_2"]: ("2BUTTON",),
		KEYIDS["KEY_3"]: ("3BUTTON",),
		KEYIDS["KEY_4"]: ("4BUTTON",),
		KEYIDS["KEY_5"]: ("5BUTTON",),
		KEYIDS["KEY_6"]: ("6BUTTON",),
		KEYIDS["KEY_7"]: ("7BUTTON",),
		KEYIDS["KEY_8"]: ("8BUTTON",),
		KEYIDS["KEY_9"]: ("9BUTTON",),
		# Front panel keys
		KEYIDS["KEY_MEDIA"]: ("FP_MEDIA",),
		KEYIDS["KEY_POWER"]: ("FP_ON_OFF",),
		KEYIDS["KEY_DOWN"]: ("FP_MINUS",),
		KEYIDS["KEY_UP"]: ("FP_PLUS",),
		KEYIDS["KEY_OK"]: ("FP_TV_R",),
	},
]

def addKeyBinding(domain, key, context, action, flags):
	keyBindings.setdefault((context, action), []).append((key, domain, flags))

# returns a list of (key, flags) for a specified action
def queryKeyBinding(context, action):
	if (context, action) in keyBindings:
		return [(x[0], x[2]) for x in keyBindings[(context, action)]]
	else:
		return [ ]

def getKeyDescription(key):
	if rc_model.rcIsDefault():
		idx = config.misc.rcused.value
	else:
		rctype = config.plugins.remotecontroltype.rctype.value
		print "[Keybindings.py] RC type is:", rctype
		rctype = 11
		if rctype == 10:	# Spark
			idx = 3
		elif rctype == 7:	# Fortis FS9000/FS9200/HS8200
			idx = 4
		elif rctype == 8:	# Fortis HS9510/HS7420/HS7429/HS7810A/HS7819
			idx = 4
		elif rctype == 9:	# Fortis HS7110/HS7119
			idx = 4
		elif rctype == 11:	# Topfield TF77X0HDPVR
			idx = 5
		elif rctype == 12:	# Kathrein UFS912
			idx = 6
		elif rctype == 13:	# CubeRevo Universal
			idx = 7
#		elif rctype == 14:	# ...
#			idx = 8
		else:
			idx = 2
	if key in keyDescriptions[idx]:
		return keyDescriptions[idx].get(key, [ ])

def removeKeyBindings(domain):
	# remove all entries of domain 'domain'
	for x in keyBindings:
		keyBindings[x] = filter(lambda e: e[1] != domain, keyBindings[x])
